"""
Singapore SkillsFuture Skills Framework data.

Sources:
- 16 Critical Core Skills (CCS): Official CCS Reference Documents from
  https://jobsandskills.skillsfuture.gov.sg/frameworks/critical-core-skills
- 38 SkillsFuture Sectors: Sector Information page at
  https://jobsandskills.skillsfuture.gov.sg/frameworks/sector-information
- SG-specific government, regulatory, and industry terms: curated from
  public sector job postings and official government websites.

Last updated: 2026-03-25
"""

from __future__ import annotations

# Grouped under 3 clusters: Thinking Critically, Interacting with Others,
# Staying Relevant. Each skill has Basic / Intermediate / Advanced levels.

CCS_CLUSTERS: dict[str, list[str]] = {
    "Thinking Critically": [
        "Creative Thinking",
        "Decision Making",
        "Problem Solving",
        "Sense Making",
        "Transdisciplinary Thinking",
    ],
    "Interacting with Others": [
        "Building Inclusivity",
        "Collaboration",
        "Communication",
        "Customer Orientation",
        "Developing People",
        "Influence",
    ],
    "Staying Relevant": [
        "Adaptability",
        "Digital Fluency",
        "Global Perspective",
        "Learning Agility",
        "Self Management",
    ],
}

# Flat set of all 16 CCS skill names (title case, matching official naming)
CCS_SKILLS: set[str] = {
    skill
    for skills in CCS_CLUSTERS.values()
    for skill in skills
}

# As listed on the Skills Framework sector information page.

SG_SECTORS: set[str] = {
    "Accountancy",
    "Aerospace",
    "Agrifood",
    "Air Transport",
    "Arts",
    "Biopharmaceuticals Manufacturing",
    "Built Environment",
    "Carbon Services and Trading",
    "Design",
    "Early Childhood",
    "Electronics",
    "Energy and Chemicals",
    "Energy and Power",
    "Engineering Services",
    "Environmental Services",
    "Financial Services",
    "Food Manufacturing",
    "Food Services",
    "Healthcare",
    "Hotel and Accommodation Services",
    "Human Resource",
    "Infocomm Technology",
    "Intellectual Property",
    "Landscape",
    "Legal Services",
    "Logistics",
    "Marine and Offshore",
    "Media",
    "Precision Engineering",
    "Public Transport",
    "Retail",
    "Sea Transport",
    "Security",
    "Social Service",
    "Tourism",
    "Training and Adult Education",
    "Wholesale Trade",
    "Workplace Safety and Health",
}

# Terms commonly found in Singapore job postings that are specific to the
# local ecosystem: government agencies, regulations, platforms, and
# certifications. All stored lowercase for case-insensitive matching.

SG_SKILLS: set[str] = {
    "creative thinking",
    "decision making",
    "problem solving",
    "sense making",
    "transdisciplinary thinking",
    "building inclusivity",
    "collaboration",
    "communication",
    "customer orientation",
    "developing people",
    "influence",
    "adaptability",
    "digital fluency",
    "global perspective",
    "learning agility",
    "self management",
    "govtech",
    "government technology agency",
    "smart nation",
    "smart nation initiative",
    "whole-of-government",
    "wog",
    "gebiz",
    "singpass",
    "corppass",
    "myinfo",
    "national digital identity",
    "ndi",
    "sgts",
    "singapore government tech stack",
    "lifesg",
    "parents gateway",
    "tracetogether",
    # Statutory boards and ministries (as they appear in JDs)
    "mas",
    "monetary authority of singapore",
    "cpf",
    "central provident fund",
    "iras",
    "inland revenue authority",
    "nea",
    "national environment agency",
    "lta",
    "land transport authority",
    "hdb",
    "housing and development board",
    "moe",
    "ministry of education",
    "moh",
    "ministry of health",
    "mom",
    "ministry of manpower",
    "mnd",
    "ministry of national development",
    "mti",
    "ministry of trade and industry",
    "mof",
    "ministry of finance",
    "mha",
    "ministry of home affairs",
    "mindef",
    "ministry of defence",
    "mci",
    "ministry of communications and information",
    "imda",
    "infocomm media development authority",
    "edb",
    "economic development board",
    "enterprise singapore",
    "a*star",
    "agency for science technology and research",
    "dsta",
    "defence science and technology agency",
    "csit",
    "centre for strategic infocomm technologies",
    "gic",
    "temasek",
    "sla",
    "singapore land authority",
    "bca",
    "building and construction authority",
    "ema",
    "energy market authority",
    "pub",
    "public utilities board",
    "nparks",
    "national parks board",
    "stb",
    "singapore tourism board",
    "ssg",
    "skillsfuture singapore",
    "wsg",
    "workforce singapore",
    "nyc",
    "national youth council",
    "nlb",
    "national library board",
    "nhb",
    "national heritage board",
    "sportsg",
    "sport singapore",
    "ntuc",
    "pdpa",
    "personal data protection act",
    "employment act",
    "workplace safety and health act",
    "wsha",
    "environmental protection and management act",
    "epma",
    "securities and futures act",
    "sfa",
    "payment services act",
    "psa",
    "cybersecurity act",
    "public sector governance act",
    "official secrets act",
    "osa",
    "instruction manual",
    "im8",
    "government instruction manual",
    "sgx",
    "singapore exchange",
    "mas regulations",
    "mas guidelines",
    "mas notice",
    "mas technology risk management",
    "trm guidelines",
    "aml/cft",
    "anti-money laundering",
    "countering the financing of terrorism",
    "kyc",
    "know your customer",
    "customer due diligence",
    "cdd",
    "enhanced due diligence",
    "edd",
    "suspicious transaction reporting",
    "str",
    "paynow",
    "fast",
    "sgqr",
    "nets",
    "giro",
    "dbs",
    "ocbc",
    "uob",
    "mas fintech",
    "project ubin",
    "project guardian",
    "payment services",
    "digital payment token",
    "national ai strategy",
    "ai governance framework",
    "model ai governance",
    "ai verify",
    "sg digital",
    "digital readiness",
    "digital ambassadors",
    "infocomm technology",
    "ict",
    "government commercial cloud",
    "gcc",
    "government data architecture",
    "apex",
    "nectar",
    "ship-hats",
    "codex",
    "isomer",
    "open government products",
    "ogp",
    "techpass",
    "skillsfuture",
    "skillsfuture credit",
    "skillsfuture enterprise credit",
    "skills framework",
    "wsq",
    "workforce skills qualifications",
    "ibd",
    "industry-based training",
    "sgunited",
    "sgunited skills",
    "sgunited traineeships",
    "critical core skills",
    "ccs",
    "national ite certification",
    "nitec",
    "higher nitec",
    "polytechnic diploma",
    "gce o-level",
    "gce a-level",
    "psle",
    "singapore-cambridge",
    "autonomous university",
    "nus",
    "national university of singapore",
    "ntu",
    "nanyang technological university",
    "smu",
    "singapore management university",
    "sutd",
    "singapore university of technology and design",
    "sit",
    "singapore institute of technology",
    "suss",
    "singapore university of social sciences",
    "bizsafe",
    "bizsafe star",
    "iso 9001",
    "iso 14001",
    "iso 27001",
    "iso 45001",
    "ss 506",
    "ss 507",
    "ss 564",
    "singapore standard",
    "spring singapore",
    "singapore quality class",
    "sqc",
    "people developer",
    "singapore certified management consultant",
    "cmc",
    "moh healthcare",
    "healthhub",
    "national electronic health record",
    "nehr",
    "synapxe",
    "ihis",
    "integrated health information systems",
    "community health assist scheme",
    "chas",
    "medisave",
    "medishield life",
    "eldershield",
    "careshield life",
    "healthcare services act",
    "hsa",
    "health sciences authority",
    "gp clinic",
    "polyclinic",
    "restructured hospital",
    "bca green mark",
    "green mark",
    "buildability score",
    "constructability score",
    "design for manufacturing and assembly",
    "dfma",
    "integrated digital delivery",
    "idd",
    "corenet",
    "corenet x",
    "registered architect",
    "professional engineer",
    "registered surveyor",
    "builders licence",
    "construction safety",
    "erp",
    "electronic road pricing",
    "one motoring",
    "mycareersfuture",
    "psi",
    "nea weather",
    "changi airport",
    "port of singapore",
    "maritime and port authority",
    "mpa",
    "civil aviation authority",
    "caas",
    "jurong port",
    "national service",
    "ns",
    "saf",
    "singapore armed forces",
    "singapore police force",
    "spf",
    "scdf",
    "singapore civil defence force",
    "ica",
    "immigration and checkpoints authority",
    "security clearance",
    "restricted",
    "confidential",
    "secret",
    "gebiz",
    "government procurement",
    "invitation to tender",
    "itt",
    "request for proposal",
    "rfp",
    "request for quotation",
    "rfq",
    "request for information",
    "rfi",
    "period contract",
    "framework agreement",
    "term contract",
    "government contract",
    "singapore green plan",
    "singapore green plan 2030",
    "green finance",
    "carbon tax",
    "carbon credits",
    "sustainability reporting",
    "environmental social governance",
    "esg",
    "green building",
    "solar energy",
    "nea carbon",
    "national wages council",
    "nwc",
    "tripartism",
    "tripartite guidelines",
    "tripartite alliance",
    "tafep",
    "fair consideration framework",
    "fcf",
    "fair employment practices",
    "progressive wage model",
    "pwm",
    "retirement and re-employment act",
    "flexible work arrangements",
    "fwa",
    "jobs growth incentive",
    "jgi",
    "wage credit scheme",
    "productivity solutions grant",
    "psg",
    "enterprise development grant",
    "edg",
    "market readiness assistance",
    "mra",
    "data.gov.sg",
    "singstat",
    "singapore department of statistics",
    "oneservice",
    "sense-making",
    "analytics-driven",
    "data-driven policy",
    "evidence-based policy",
}


# Lowercase versions of sectors for case-insensitive matching
SG_SECTORS_LOWER: set[str] = {s.lower() for s in SG_SECTORS}

# Lowercase versions of CCS skills
CCS_SKILLS_LOWER: set[str] = {s.lower() for s in CCS_SKILLS}

# Combined: all SG-specific terms (SG_SKILLS already lowercase)
# plus lowercase sector names and CCS skill names
ALL_SG_TERMS: set[str] = SG_SKILLS | SG_SECTORS_LOWER | CCS_SKILLS_LOWER
