from .coordinator import COORDINATOR_PROMPT_VERSION, COORDINATOR_SYSTEM_PROMPT
from .role_success import ROLE_SUCCESS_PROMPT_VERSION, ROLE_SUCCESS_SYSTEM_PROMPT

__all__ = [
    "COORDINATOR_PROMPT_VERSION",
    "COORDINATOR_SYSTEM_PROMPT",
    "ROLE_SUCCESS_PROMPT_VERSION",
    "ROLE_SUCCESS_SYSTEM_PROMPT",
]
