// Resume-related constants extracted from App.jsx (Phase 3)

export const DEFAULT_RESUME_TEMPLATES = [
  {
    id: "classic",
    name: "Classic",
    description: "Traditional serif layout with crisp section dividers.",
    font: "Times New Roman",
    body_size: 11,
    name_size: 16,
    margins: 1.0,
    section_order: ["summary", "education", "experience", "skills", "certifications"],
  },
  {
    id: "modern",
    name: "Modern",
    description: "Sharper hierarchy for technical and startup roles.",
    font: "Calibri",
    body_size: 10,
    name_size: 14,
    margins: 0.6,
    section_order: ["summary", "experience", "projects", "skills", "education"],
  },
  {
    id: "singapore",
    name: "SG Pro",
    description: "Polished local-market style with balanced spacing.",
    font: "Calibri",
    body_size: 11,
    name_size: 15,
    margins: 0.8,
    section_order: ["personal", "summary", "education", "experience", "activities", "skills"],
  },
  {
    id: "compact",
    name: "Compact",
    description: "Tighter layout for experienced candidates.",
    font: "Arial",
    body_size: 10,
    name_size: 14,
    margins: 0.5,
    section_order: ["summary", "experience", "skills", "education", "certifications"],
  },
  {
    id: "executive",
    name: "Executive",
    description: "Large name, gray header bar for C-suite and VP roles.",
    font: "Georgia",
    body_size: 11,
    name_size: 20,
    margins: 1.0,
    section_order: ["summary", "experience", "education", "skills", "certifications"],
  },
  {
    id: "creative",
    name: "Creative",
    description: "Indigo accent with colored borders for design and marketing.",
    font: "Calibri",
    body_size: 10,
    name_size: 16,
    margins: 0.75,
    section_order: ["summary", "experience", "projects", "skills", "education"],
  },
  {
    id: "technical",
    name: "Technical",
    description: "Monospace headings, skills-first for engineering roles.",
    font: "Calibri",
    body_size: 10,
    name_size: 14,
    margins: 0.6,
    section_order: ["summary", "skills", "experience", "projects", "education", "certifications"],
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "No borders, no backgrounds. Maximum ATS compatibility.",
    font: "Calibri",
    body_size: 11,
    name_size: 15,
    margins: 0.8,
    section_order: ["summary", "experience", "education", "skills"],
  },
];

export const RESUME_TEMPLATE_STYLES = {
  classic: {
    pageClass: "text-stone-800",
    fontFamily: '"Times New Roman", Georgia, serif',
    bodySize: 11,
    nameSize: 16,
    margins: 1.0,
    lineHeight: 1.35,
    headingSize: 12,
    headingClass: "mt-4 mb-1 border-b border-stone-400 pb-1 font-bold uppercase tracking-[0.18em] text-stone-900",
    nameClass: "font-bold tracking-[0.08em] text-stone-950",
    subheadingClass: "mt-2 mb-0.5 text-stone-700",
  },
  modern: {
    pageClass: "text-slate-800",
    fontFamily: 'Calibri, "Segoe UI", sans-serif',
    bodySize: 10,
    nameSize: 14,
    margins: 0.6,
    lineHeight: 1.33,
    headingSize: 11,
    headingClass: "mt-4 mb-1 border-b border-indigo-500 pb-1 font-bold uppercase tracking-[0.18em] text-slate-900",
    nameClass: "font-bold tracking-[0.04em] text-slate-950",
    subheadingClass: "mt-2 mb-0.5 text-slate-700",
  },
  singapore: {
    pageClass: "text-slate-800",
    fontFamily: 'Calibri, "Segoe UI", sans-serif',
    bodySize: 11,
    nameSize: 15,
    margins: 0.8,
    lineHeight: 1.35,
    headingSize: 12,
    headingClass: "mt-4 mb-1 border-b-2 border-slate-700 pb-1 font-bold uppercase tracking-[0.16em] text-slate-950",
    nameClass: "font-bold tracking-[0.04em] text-slate-950",
    subheadingClass: "mt-2 mb-0.5 text-slate-700",
  },
  compact: {
    pageClass: "text-zinc-800",
    fontFamily: "Arial, Helvetica, sans-serif",
    bodySize: 10,
    nameSize: 14,
    margins: 0.5,
    lineHeight: 1.3,
    headingSize: 11,
    headingClass: "mt-4 mb-1 border-b border-zinc-400 pb-1 font-bold uppercase tracking-[0.14em] text-zinc-950",
    nameClass: "font-bold tracking-[0.03em] text-zinc-950",
    subheadingClass: "mt-2 mb-0.5 text-zinc-700",
  },
  executive: {
    pageClass: "text-gray-800",
    fontFamily: "Georgia, \"Times New Roman\", serif",
    bodySize: 11,
    nameSize: 20,
    margins: 1.0,
    lineHeight: 1.4,
    headingSize: 13,
    headingClass: "mt-6 mb-2 border-b border-gray-300 pb-1 font-semibold uppercase tracking-[0.22em] text-gray-700",
    nameClass: "font-bold tracking-[0.06em] text-gray-950",
    subheadingClass: "mt-3 mb-1 text-gray-700",
  },
  creative: {
    pageClass: "text-gray-800",
    fontFamily: "Calibri, \"Segoe UI\", sans-serif",
    bodySize: 10,
    nameSize: 16,
    margins: 0.75,
    lineHeight: 1.35,
    headingSize: 12,
    headingClass: "mt-4 mb-1 border-l-4 border-indigo-500 pl-3 font-bold uppercase tracking-[0.14em] text-indigo-700",
    nameClass: "font-bold tracking-[0.04em] text-indigo-900",
    subheadingClass: "mt-2 mb-0.5 text-gray-700",
  },
  technical: {
    pageClass: "text-slate-800",
    fontFamily: "Calibri, \"Segoe UI\", sans-serif",
    bodySize: 10,
    nameSize: 14,
    margins: 0.6,
    lineHeight: 1.3,
    headingSize: 11,
    headingClass: "mt-3 mb-1 border-b border-slate-300 pb-0.5 font-bold uppercase tracking-[0.12em] text-slate-900 font-mono",
    nameClass: "font-bold tracking-[0.03em] text-slate-950 font-mono",
    subheadingClass: "mt-1.5 mb-0.5 text-slate-700",
  },
  minimal: {
    pageClass: "text-gray-800",
    fontFamily: "Calibri, \"Segoe UI\", sans-serif",
    bodySize: 11,
    nameSize: 15,
    margins: 0.8,
    lineHeight: 1.35,
    headingSize: 12,
    headingClass: "mt-5 mb-1 font-bold uppercase tracking-[0.16em] text-gray-900",
    nameClass: "font-bold tracking-[0.04em] text-gray-950",
    subheadingClass: "mt-2 mb-0.5 text-gray-700",
  },
};

export const NUS_RESUME_BENCHMARKS = [
  {
    value: "490",
    label: "Average words seen across NUS resumes, not a hard cap",
  },
  {
    value: "21",
    label: "Average bullets in stronger resume drafts",
  },
  {
    value: "16",
    label: "Action verbs often seen in 80+ scoring resumes",
  },
  {
    value: "25",
    label: "Specifics or quantified cues in stronger resumes",
  },
  {
    value: "4-5",
    label: "Section headings most resumes tend to carry",
  },
];

export const RESUME_HEADINGS = new Set([
  "summary",
  "professional summary",
  "executive summary",
  "career summary",
  "professional profile",
  "profile",
  "summary of qualifications",
  "qualifications",
  "experience",
  "professional experience",
  "work experience",
  "employment history",
  "career history",
  "work and internship experience",
  "work and internship experiences",
  "internship and work experience",
  "education",
  "academic background",
  "skills",
  "skills & interests",
  "skills and interests",
  "core skills",
  "technical skills",
  "technical proficiencies",
  "core competencies",
  "competencies",
  "projects",
  "selected projects",
  "leadership",
  "activities",
  "activities & leadership",
  "certifications",
  "certification",
  "licenses",
  "licenses & certifications",
  "certifications & technical upskilling",
  "awards",
  "volunteer",
  "volunteering",
  "interests",
  "languages",
  "languages & work authorization",
  "additional information",
  "co-curricular experience",
  "extra-curriculars",
  "personal",
  "personal particulars",
]);

export const RESUME_TEMPLATE_SECTION_ORDER = {
  classic: ["summary", "education", "experience", "skills", "certifications"],
  modern: ["summary", "experience", "projects", "skills", "education"],
  singapore: ["personal", "summary", "education", "experience", "activities", "skills"],
  compact: ["summary", "experience", "skills", "education", "certifications"],
};

export const RESUME_ACTION_VERBS = new Set([
  "achieved", "administered", "advanced", "analyzed", "architected",
  "assembled", "assessed", "automated", "built", "calculated",
  "championed", "coached", "collaborated", "communicated", "completed",
  "conceptualized", "conducted", "consolidated", "constructed",
  "consulted", "contributed", "controlled", "converted", "coordinated",
  "created", "cultivated", "customized", "decreased", "defined",
  "delivered", "demonstrated", "deployed", "designed", "developed",
  "devised", "diagnosed", "directed", "discovered", "documented",
  "drove", "earned", "edited", "educated", "eliminated", "enabled",
  "encouraged", "engineered", "enhanced", "established", "evaluated",
  "examined", "exceeded", "executed", "expanded", "expedited",
  "facilitated", "finalized", "forecasted", "formulated", "founded",
  "generated", "governed", "guided", "headed", "identified",
  "illustrated", "implemented", "improved", "increased", "influenced",
  "initiated", "innovated", "inspected", "installed", "instituted",
  "integrated", "interpreted", "introduced", "invented", "investigated",
  "launched", "led", "leveraged", "maintained", "managed", "mapped",
  "maximized", "mentored", "merged", "migrated", "minimized",
  "modernized", "monitored", "motivated", "navigated", "negotiated",
  "operated", "optimized", "orchestrated", "organized", "originated",
  "outperformed", "overhauled", "oversaw", "partnered", "performed",
  "piloted", "pioneered", "planned", "prepared", "presented",
  "prioritized", "produced", "programmed", "promoted", "proposed",
  "provided", "published", "pursued", "reached", "realized",
  "recommended", "reconciled", "recruited", "redesigned", "reduced",
  "refined", "reformed", "regulated", "reorganized", "represented",
  "researched", "resolved", "restructured", "revamped", "reviewed",
  "scaled", "secured", "simplified", "solved", "spearheaded",
  "standardized", "streamlined", "strengthened", "structured",
  "supervised", "surpassed", "sustained", "synchronized", "targeted",
  "tested", "trained", "transformed", "translated", "troubleshot",
  "unified", "upgraded", "validated", "verified", "visualized",
]);

export const RESUME_AVOIDED_PHRASES = [
  "responsible for",
  "helped",
  "assisted",
  "duties included",
  "various",
  "utilized",
  "proactively",
];

export const BULLET_ACTION_SUGGESTIONS = [
  "Administered",
  "Customized",
  "Facilitated",
  "Implemented",
  "Managed",
  "Optimized",
  "Orchestrated",
  "Spearheaded",
];

export const RESUME_WEAK_STARTS = ["responsible for", "helped", "assisted"];
export const RESUME_BULLET_RE = /^(\s*(?:[-*o\u2022\u2023\u25E6\u2043\u2219\u25AA\u25AB\u25CF\uF0B7▪●]|\d+[.)]))\s*(.*)$/;
export const RESUME_METRIC_RE = /\d+%|\$[\d,]+|\d+\s*(?:users|user|team|people|projects|systems|clients|hours|weeks|months|years)|\d+[kKmMbB]\b|\d{1,3}(?:,\d{3})+/;
export const RESUME_SCALE_CUE_PATTERNS = [
  /\bteam of \d+\b/gi,
  /\b\d+\s+(?:direct|indirect)\s+reports?\b/gi,
  /\b\d+\s+(?:reports?|engineers?|specialists?|operators?|owners?|stakeholders?|people|users?|clients?|projects?|systems?|hours?|weeks?|months?|years?|sites?|fabs?|fab\s+lines?|lines?|plants?|dashboards?|sensors?|parameters?|countries?|regions?|modules?|tools?)\b/gi,
  /\b(?:across|over|under|up to|more than|less than|nearly|almost)\s+\d+(?:\.\d+)?\s+(?:sites?|fabs?|fab\s+lines?|lines?|plants?|regions?|countries?|teams?|people|users?|projects?|systems?|clients?|engineers?|specialists?|reports?|hours?|weeks?|months?|years?|dashboards?|sensors?|parameters?)\b/gi,
];
export const RESUME_DATE_HINT_RE = /\b(?:19|20)\d{2}\b|present|current|jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec/i;
export const RESUME_CERTIFICATION_RE = /certification|certifications|certificate|certified|pmp|wsq|skillsfuture|accredited|in progress|target|gmat|upskilling|emeritus|heicoders|completed.*course|full stack development|generative ai|currently pursuing/i;
export const RESUME_EDUCATION_RE = /\b(?:university|polytechnic|college|school|institute|academy|faculty|gpa|degree|diploma|bachelor|master|ph\.?d|exchange|graduated|major|minor|focus|capstone|national university|nanyang|singapore management|nus|ntu|smu|sutd|sit|suss)\b/i;
export const RESUME_EDUCATION_INSTITUTION_RE = /\b(?:university|polytechnic|college|school|institute|academy|faculty|national university|nanyang|singapore management|nus|ntu|smu|sutd|sit|suss|temasek poly|ngee ann|republic poly|singapore poly|nyp|ite college|kaplan|lasalle|nafa|sim global|psb academy|james cook university|curtin university|monash university|eth zurich|university of melbourne|university of sydney|unsw|hku|tsinghua|peking university)\b/i;
export const RESUME_DEGREE_RE = /\b(?:b\.?sc|m\.?sc|b\.?eng|m\.?eng|b\.?a|m\.?a|bachelor|master|ph\.?d|doctorate|diploma|advanced diploma|associate|degree|mba|certificate|cert)\b/i;
export const DEGREE_START_RE = /^(M\.?Sc|B\.?Sc|B\.?Eng|MBA|M\.?Eng|Ph\.?D|B\.?A|M\.?A|Diploma|Advanced Diploma|Associate|Graduate Cert(?:ificate)?|Certificate|Cert)/i;
export const RESUME_EDUCATION_DETAIL_RE = /gpa|exchange|focus|capstone|graduate certificate|graduate certificates|minor|major|distinction|honou?r/i;
export const RESUME_OVERUSED_IGNORE = new Set([
  "automation", "digital", "transformation", "program", "manager", "management",
  "yield", "data", "analytics", "analysis", "operations", "engineering",
  "technology", "technologies", "quality", "process", "processes", "project",
  "projects", "stakeholder", "stakeholders", "cross", "functional", "global",
  "system", "systems", "team", "teams", "experience", "skills", "education",
  "resume", "singapore", "micron", "ai", "ml", "reliability",
]);
export const RESUME_DISPLAY_ACRONYMS = new Set([
  "AI", "ML", "APAC", "ROI", "KPI", "SQL", "API", "APIs", "USD", "RCA", "SPC",
  "EQMS", "IT", "OT", "IT/OT", "DOE", "DoE", "RPA", "NPI", "NUS", "SG",
  "FEOL", "FE", "BE", "HBM3E", "LPDDR5X", "TTMCY", "RAG", "MCP", "WSQ",
  "PMP", "GMAT", "GCP",
]);
export const RESUME_SMALL_TITLE_WORDS = new Set([
  "a", "an", "and", "as", "at", "by", "for", "from", "in", "into", "of",
  "on", "or", "the", "to", "with",
]);
export const RESUME_SECTION_LABELS = {
  summary: "Professional Summary",
  objective: "Objective",
  experience: "Professional Experience",
  education: "Education",
  skills: "Core Skills",
  projects: "Projects",
  certifications: "Certifications",
  activities: "Volunteer & Leadership",
  personal: "Additional Information",
  languages: "Languages",
  awards: "Awards",
};
export const TAILOR_STAGE_LABELS = [
  { id: "analyze", label: "Analyze" },
  { id: "strategize", label: "Strategy" },
  { id: "local_cleanup", label: "Cleanup" },
  { id: "bullet_rewrite", label: "Rewrite" },
  { id: "section_polish", label: "Polish" },
  { id: "full_polish", label: "Summary" },
  { id: "validate", label: "Validate" },
];
export const ADD_SECTION_OPTIONS = [
  { id: "summary", label: "Professional Summary", heading: "PROFESSIONAL SUMMARY", starter: "Add a concise summary of your fit, scope, and focus areas here." },
  { id: "projects", label: "Projects", heading: "PROJECTS", starter: "• Add project details here" },
  { id: "certifications", label: "Certifications", heading: "CERTIFICATIONS", starter: "• Add certification or ongoing credential here" },
  { id: "languages", label: "Languages", heading: "LANGUAGES", starter: "Add languages and proficiency here." },
  { id: "volunteer", label: "Volunteer", heading: "VOLUNTEER EXPERIENCE", starter: "• Add volunteer experience here" },
  { id: "awards", label: "Awards", heading: "AWARDS", starter: "• Add award or recognition here" },
  { id: "custom", label: "Custom", heading: "", starter: "• Add details here" },
];

export const KEYWORD_INSERT_PREFERRED_SECTIONS = new Set([
  "experience", "projects", "skills", "technical",
  "work experience", "professional experience",
  "achievements", "accomplishments",
]);
